package view;

import java.io.File;
import java.io.FileInputStream;
import DAO.Caminhos;
import FileSystemModel.FileSystemModel;
import WriteFiles.WriteFiles;
import diretorio.CSVFile;
import java.awt.Desktop;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
import sird.Main;

public class Controle extends javax.swing.JFrame {

    String caminho;
    String nomeArquivo;

    /**
     * Creates new form Controle
     */
    public Controle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnAbrir = new javax.swing.JButton();
        jBtnRemover = new javax.swing.JButton();
        jBtnRecuperar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jBtnInserir1 = new javax.swing.JButton();
        jBtnBuscar = new javax.swing.JButton();
        jBtnIndexar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jBtnExecutar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnAbrir.setText("Abrir");
        jBtnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAbrirActionPerformed(evt);
            }
        });

        jBtnRemover.setText("Remover");
        jBtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoverActionPerformed(evt);
            }
        });

        jBtnRecuperar.setText("Recuperar");
        jBtnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRecuperarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("C:");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Users");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("gioto");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Documents");
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("NetBeansProjects");
        javax.swing.tree.DefaultMutableTreeNode treeNode6 = new javax.swing.tree.DefaultMutableTreeNode("TDE");
        javax.swing.tree.DefaultMutableTreeNode treeNode7 = new javax.swing.tree.DefaultMutableTreeNode("src");
        javax.swing.tree.DefaultMutableTreeNode treeNode8 = new javax.swing.tree.DefaultMutableTreeNode("doc");
        javax.swing.tree.DefaultMutableTreeNode treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc1.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc2.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc3.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc4.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc5.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc6.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc7.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc8.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc9.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc10.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc11.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc12.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc13.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc14.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc15.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc16.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc17.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc18.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc19.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc20.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc21.txt");
        treeNode8.add(treeNode9);
        treeNode9 = new javax.swing.tree.DefaultMutableTreeNode("doc22.txt");
        treeNode8.add(treeNode9);
        treeNode7.add(treeNode8);
        treeNode6.add(treeNode7);
        treeNode5.add(treeNode6);
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        jBtnInserir1.setText("Substituir");
        jBtnInserir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInserir1ActionPerformed(evt);
            }
        });

        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        jBtnIndexar.setText("Indexar");
        jBtnIndexar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIndexarActionPerformed(evt);
            }
        });

        jBtnModificar.setText("Acrescentar");
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        jBtnExecutar.setText("Consultar");
        jBtnExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtnRemover, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnIndexar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnRecuperar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnInserir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnExecutar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 15, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnBuscar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAbrir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnExecutar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnInserir1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnRecuperar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnIndexar)
                                .addGap(12, 12, 12))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAbrirActionPerformed
        try {
            //CSVFile cv = new CSVFile();
            //cv.abrirArquivoDeLeitura(caminho, nomeArquivo);
            File arquivo = new File(caminho);
            if (arquivo.exists()) {
                if (Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(arquivo);
                }
            }
        } catch (Exception ex) {
        }


    }//GEN-LAST:event_jBtnAbrirActionPerformed

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked

        caminho = jTree1.getSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "\\");
        nomeArquivo = jTree1.getLastSelectedPathComponent().toString();
        jTextField1.setText(caminho);
        jTextField1.setText(jTree1.getSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "\\"));

        Caminhos c = new Caminhos();
        c.setCaminho(caminho);
        c.setNomeArquivo(nomeArquivo);
        String casa = c.getNomeArquivo();
//        jTextField1.setText(casa);
    }//GEN-LAST:event_jTree1MouseClicked

    private void jBtnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRecuperarActionPerformed
        File file = new File(caminho);
        FileInputStream fis = null;
        String texto = "";

        try {
            fis = new FileInputStream(file);
            int content;
            while ((content = fis.read()) != -1) {
                texto += (char) content;
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (fis != null) {
                    fis.close();
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        JTextArea textArea = new JTextArea(texto);
        textArea.setLineWrap(true); //quebra de linha automática
        jTextArea1.setText(texto);


    }//GEN-LAST:event_jBtnRecuperarActionPerformed

    private void jBtnInserir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInserir1ActionPerformed
        //String cami = jTextField1.getText();
        File file = new File(caminho);
        file.delete();
        String Texto = jTextArea1.getText();
        try {
            File arquivo = new File("C:\\Users\\gioto\\Documents\\NetBeansProjects\\TDE\\src\\doc\\");
            int aux = 0;
            File[] arquivos = arquivo.listFiles();
            if (arquivos != null) {
                int length = arquivos.length;
                for (int i = 0; i < length; ++i) {
                    File f = arquivos[i];
                    if (f.isFile()) {
                        aux++;
                    }
                }

            }
            Caminhos c = new Caminhos();
            FileOutputStream fos;

            fos = new FileOutputStream("C:\\Users\\gioto\\Documents\\NetBeansProjects\\TDE\\src\\doc\\" + nomeArquivo, true);
            PrintStream ps = new PrintStream(fos);
            ps.print(Texto);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Controle.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("█████████████▀▀▀▀▀▀▀▀▀▀▀▀▀█████████████\n" +
"████████▀▀░░░░░░░░░░░░░░░░░░░▀▀████████\n" +
"██████▀░░░░░░░░░░░░░░░░░░░░░░░░░▀██████\n" +
"█████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█████\n" +
"████░░░░░▄▄▄▄▄▄▄░░░░░░░░▄▄▄▄▄▄░░░░░████\n" +
"████░░▄██████████░░░░░░██▀░░░▀██▄░░████\n" +
"████░░███████████░░░░░░█▄░░▀░░▄██░░████\n" +
"█████░░▀▀███████░░░██░░░██▄▄▄█▀▀░░█████\n" +
"██████░░░░░░▄▄▀░░░████░░░▀▄▄░░░░░██████\n" +
"█████░░░░░█▄░░░░░░▀▀▀▀░░░░░░░█▄░░░█████\n" +
"█████░░░▀▀█░█▀▄▄▄▄▄▄▄▄▄▄▄▄▄▀██▀▀░░█████\n" +
"██████░░░░░▀█▄░░█░░█░░░█░░█▄▀░░░░██▀▀▀▀\n" +
"▀░░░▀██▄░░░░░░▀▀█▄▄█▄▄▄█▄▀▀░░░░▄█▀░░░▄▄\n" +
"▄▄▄░░░▀▀██▄▄▄▄░░░░░░░░░░░░▄▄▄███░░░▄██▄\n" +
"██████▄▄░░▀█████▀█████▀██████▀▀░░▄█████\n" +
"██████████▄░░▀▀█▄░░░░░▄██▀▀▀░▄▄▄███▀▄██\n" +
"███████████░██░▄██▄▄▄▄█▄░▄░████████░███");
    }//GEN-LAST:event_jBtnInserir1ActionPerformed

    private void jBtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoverActionPerformed
        //String cami = jTextField1.getText();
        File file = new File(caminho);
        file.delete();

    }//GEN-LAST:event_jBtnRemoverActionPerformed

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        String cami = jTextField1.getText();
        try {
            //CSVFile cv = new CSVFile();
            //cv.abrirArquivoDeLeitura(caminho, nomeArquivo);
            File arquivo = new File(cami);
            if (arquivo.exists()) {
                if (Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(arquivo);

                }
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jBtnIndexarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIndexarActionPerformed
        try {

            WriteFiles fl = new WriteFiles();
            String Texto = jTextArea1.getText();
            fl.gravarText(Texto);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Controle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnIndexarActionPerformed

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        String Texto = jTextArea1.getText();
        try {
            File arquivo = new File("C:\\Users\\gioto\\Documents\\NetBeansProjects\\TDE\\src\\doc\\");
            int aux = 0;
            File[] arquivos = arquivo.listFiles();
            if (arquivos != null) {
                int length = arquivos.length;
                for (int i = 0; i < length; ++i) {
                    File f = arquivos[i];
                    if (f.isFile()) {
                        aux++;
                    }
                }

            }
            Caminhos c = new Caminhos();
            FileOutputStream fos;

            fos = new FileOutputStream("C:\\Users\\gioto\\Documents\\NetBeansProjects\\TDE\\src\\doc\\" + nomeArquivo, true);
            PrintStream ps = new PrintStream(fos);
            ps.print(Texto);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Controle.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jBtnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExecutarActionPerformed
        Main main = new Main();
        main.comeco();
    }//GEN-LAST:event_jBtnExecutarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAbrir;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnExecutar;
    private javax.swing.JButton jBtnIndexar;
    private javax.swing.JButton jBtnInserir1;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnRecuperar;
    private javax.swing.JButton jBtnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
